version: 2.1

orbs: 
  slack: circleci/slack@4.9.3

executors:
  nodejs-executor:
    docker:
      - image: circleci/node:14.4.0

commands:
  print:
    description: "A simple echo"
    parameters:
      message:
        type: string
    steps:
      - run:
          name: Print a message
          command: echo Hello << parameters.message >> 

  notify-success:
    description: "Custom slack notification"
    steps:
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A $CIRCLE_JOB job has succeeded :white_check_mark:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Project:* $CIRCLE_PROJECT_REPONAME"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "value": "view_job",
                    "url": "${CIRCLE_BUILD_URL}",
                    "action_id": "button-action"
                  }
                }
              ]
            }
            
            
            
  notify-error:
    description: "Custom slack notification"
    parameters:
      message:
        type: string
        default: ""
    steps:
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "A $CIRCLE_JOB job has failed :red_circle:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Project:* $CIRCLE_PROJECT_REPONAME"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "View Job"
                    },
                    "value": "view_job",
                    "url": "$CIRCLE_BUILD_URL",
                    "action_id": "button-action"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "<<parameters.message>>"
                  }
                }
              ]
            }


     


jobs:
  build-and-push-image:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - print:
            message: "build and push"

        - notify-success
        - notify-error


  deploy-test-env:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - print:
            message: "deploying test env"
        - notify-success
        - notify-error
        
  deploy-to-staging:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - print:
            message: "deploying staging env"
        - notify-success
        - notify-error
  integration-tests:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - checkout
        - print:
            message: "running integration tests"

        - run:
              name: Run integration tests
              command: |
                  NUMBER_OF_FAILING_TESTS=1
                  FAILING_TESTS="1 failing
                  1 failing

                  1) Acceptance: Deposits
                      [Contract / Blockchain Interaction]
                        (wait for deposit transactions to complete):
                    Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()"" is called; if returning a Promise, ensure it resolves. (/code/dist/tests/acceptance/z-api-deposits.js)
                      at listOnTimeout (node:internal/timers:559:17)
                      at processTimers (node:internal/timers:502:7)"
                  FAILING_TESTS=$(echo $FAILING_TESTS
                  echo $NUMBER_OF_FAILING_TESTS
                  echo "${FAILING_TESTS}"
                  echo export TESTS_FAIL_MESSAGE=\" 🔴 A run-integration-tests job has failed!! ${FAILING_TESTS} \" >> $BASH_ENV
                  bash ./.circleci/scripts/integration_test.sh
        - notify-success
        - notify-error:
            message: $TESTS_FAIL_MESSAGE
            
  acceptance-tests:
    docker:
        - image:  cimg/python:3.8.4 

    steps:
        - checkout
        - print:
            message: "running acceptance tests"

        - run:
              name: Run acceptsance tests
              command: |
                  bash ./.circleci/scripts/acceptance_test.sh  
        - notify-success
        - notify-error:
            message: "Some error"

workflows:
  version: 2.1
  deploy-staging:
      jobs:
          - build-and-push-image
             
          - deploy-test-env:
              requires:
                - build-and-push-image
         
          - deploy-to-staging:
              requires:
                - build-and-push-image
             
          - integration-tests:
              requires:
                - deploy-test-env
            
          - acceptance-tests:
              requires:
                - deploy-to-staging
          
          