version: 2.1

orbs: 
  slack: circleci/slack@4.9.3

executors:
  nodejs-executor:
    docker:
      - image: circleci/node:14.4.0

commands:
  print:
    description: "A simple echo"
    parameters:
      message:
        type: string
    steps:
      - run:
          name: Print a message
          command: echo Hello << parameters.message >> 

  notify-slack:
    steps:
        description: "Custom slack notification"
      - slack/notify:
          event: pass
          custom: |
            {
              "text": "CircleCI job succeeded!",              
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "Job Successful. :tada:",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Env*: some-text"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Job*: ${CIRCLE_JOB}"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
      - slack/notify:
          event: fail
          custom: |           
              {
                "text": "CircleCI job failed!",              
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "Job Successful. :tada:",
                      "emoji": true
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Env*: some-text"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Job*: ${CIRCLE_JOB}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Branch*: $CIRCLE_BRANCH"
                      }
                    ]
                  },
                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "View Job"
                        },
                        "url": "${CIRCLE_BUILD_URL}"
                      }
                    ]
                  }
                ]
              }


jobs:
  build-and-push-image:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - print:
            message: "build and push"

        - notify-slack


  deploy-test-env:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - print:
            message: "deploying test env"
        - slack/notify:
            event: fail
            template: basic_fail_1
        - slack/notify:
            event: pass
            template: success_tagged_deploy_1

  deploy-to-staging:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - print:
            message: "deploying staging env"
        - notify-slack

  integration-tests:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - checkout
        - print:
            message: "running integration tests"

        - run:
              name: Run integration tests
              command: |
                  bash ./.circleci/scripts/integration_test.sh
        - notify-slack
  
  acceptance-tests:
    docker:
        - image:  cimg/python:3.8.4

    steps:
        - checkout
        - print:
            message: "running acceptance tests"

        - run:
              name: Run integration tests
              command: |
                  bash ./.circleci/scripts/acceptance_test.sh  
        - notify-slack

workflows:
  version: 2.1
  deploy-staging:
      jobs:
          - build-and-push-image
             
          - deploy-test-env:
              requires:
                - build-and-push-image
         
          - deploy-to-staging:
              requires:
                - build-and-push-image
             
          - integration-tests:
              requires:
                - deploy-test-env
            
          - acceptance-tests:
              requires:
                - deploy-to-staging
          
          